pull_request_rules:
  - name: backport to galactic at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-galactic"
    actions:
      backport:
        branches:
          - galactic

  - name: backport to foxy at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-foxy"
    actions:
      backport:
        branches:
          - foxy

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
 
