sudo: required

language:
  - none

services:
  - docker

notifications:
  email:
    on_pull_requests: false
    on_success: change
    on_failure: change
    recipients:
      - stevenmacenski@gmail.com
      - mohammad.haghighipanah@intel.com
      - michael.jeronimo@intel.com
      - carlos.a.orduno@intel.com
      - carl.r.delsey@intel.com
      - matthew.k.hansen@intel.com

before_install:
  - if [ "${TRAVIS_REPO_SLUG}" != "ros-planning/navigation2" ]; then echo "Travis CI is supported only in ros-planning/navigation2" && exit 1; fi
  - docker build -t nav2:latest --build-arg PULLREQ=$TRAVIS_PULL_REQUEST .

script:
  - docker run --name nav2_bash --rm -d -i -t --net=host nav2:latest bash -l
  - docker exec nav2_bash bash -c '. /ros2_ws/navigation2_ws/install/setup.bash &&
      colcon test --packages-skip nav2_system_tests'
  - docker exec nav2_bash bash -c "colcon test-result --verbose"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "Successfully built! Deploying container..."
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push stevemacenski/navigation2:latest ;
    fi
