sudo: required

language:
  - none

services:
  - docker

notifications:
  email:
    on_pull_requests: false
    on_success: change
    on_failure: change
    recipients:
      - stevenmacenski@gmail.com
      - mohammad.haghighipanah@intel.com
      - michael.jeronimo@intel.com
      - carlos.a.orduno@intel.com
      - brian.wilcox@intel.com
      - matthew.k.hansen@intel.com

before_install:
  - docker build -t nav2:latest --build-arg PULLREQ=$TRAVIS_PULL_REQUEST .

script:
  - docker run --name nav2_bash --rm -d -i -t nav2:latest bash -l
  - docker exec nav2_bash bash -c "colcon test --packages-skip
      dwb_controller dwb_core nav2_amcl nav2_costmap_2d nav2_dynamic_params 
      nav2_map_server nav2_smart_planner nav2_system_tests nav2_tasks 
      nav2_util nav2_voxel_grid costmap_queue dwb_critics dwb_plugins 
      nav2_bt_navigator nav2_mission_executor nav2_robot 
      nav2_simple_navigator nav2_world_model nav_2d_utils"
  - docker exec nav2_bash bash -c "colcon test-result" 
