# The map server initializes its parameters in the code. The parameters can
# be overridden by using a YAML file like this one with the following section.
# These values are the same defaults as in the code.
map_server:
    ros__parameters:
        map_name: "test_map.pgm"
        map_type: "occupancy"
        resolution: 0.1
        negate: 0
        occupied_thresh: 0.65
        free_thresh: 0.196
        mode: "trinary"
        origin: [-15.400000, -12.200000, 0.000000]
