collision_monitor_node:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_topic: "/odom"
    polygon_topic: "polygons"
    cmd_vel_in_topic: "/cmd_vel_raw"
    cmd_vel_out_topic: "/cmd_vel"
    transform_tolerance: 0.1
    max_time_shift: 10.0
    simulation_time_step: 0.02
    release_step: 0.002
    polygons: ["PolygonStop"]
    PolygonStop:
      type: "polygon"
      points: [0.5, 0.5, 0.5, -0.5, -0.1, -0.5, -0.1, 0.5, 0.5, 0.5]
      action_type: "stop"
      stop_points: 5
    PolygonApp:
      type: "polygon"
      points: [0.15, 0.15, 0.15, -0.15, -0.15, -0.15, -0.15, 0.15, 0.15, 0.15]
      action_type: "approach"
      time_before_crash: 2.0
    PolygonSlow:
      type: "polygon"
      points: [0.5, 0.5, 0.5, -0.5, -0.1, -0.5, -0.1, 0.5, 0.5, 0.5]
      action_type: "slowdown"
      stop_points: 5
      slowdown: 0.3
    CircleStop:
      type: "circle"
      radius: 0.5
      action_type: "stop"
      stop_points: 5
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
    pointcloud:
      type: "pointcloud"
      topic: "/intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5
