collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_topic: "/odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.1
    data_timeout: 5.0
    simulation_time_step: 0.02
    release_acceleration: 0.1
    polygons: ["PolygonStop"]
    PolygonStop:
      type: "polygon"
      points: [0.5, 0.5, 0.5, -0.5, -0.1, -0.5, -0.1, 0.5, 0.5, 0.5]
      action_type: "stop"
      max_points: 3
      visualize: True
      polygon_topic: "polygon_stop"
    PolygonSlow:
      type: "polygon"
      points: [0.5, 0.5, 0.5, -0.5, -0.1, -0.5, -0.1, 0.5, 0.5, 0.5]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.3
      visualize: True
      polygon_topic: "polygon_slowdown"
    CircleApp:
      type: "circle"
      radius: 0.25
      action_type: "approach"
      time_before_collision: 2.0
      visualize: True
      polygon_topic: "circle_approach"
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
    pointcloud:
      type: "pointcloud"
      topic: "/intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5
