"clean.packages":
  "test-result-base": "test_result"
"build":
  "executor": "parallel"
  "parallel-workers": 2
  "symlink-install": true
"test":
  "test-result-base": "test_result"
"test-result":
  "test-result-base": "test_result"
