map_server_3d_n1:
  ros__parameters:
    yaml_filename: "./point_cloud_map.yaml"
map_server_3d_n2:
  ros__parameters:
    yaml_filename: "./point_cloud_map.yaml"
map_server_3d_n3:
  ros__parameters:
    yaml_filename: "./point_cloud_map.yaml"
map_server_3d_n4:
  ros__parameters:
    yaml_filename: "./point_cloud_map.yaml"
