map_server_2d_n1:
  ros__parameters:
    yaml_filename: "./occupancy_grid_map.yaml"
map_server_2d_n2:
  ros__parameters:
    yaml_filename: "./occupancy_grid_map.yaml"
map_server_2d_n3:
  ros__parameters:
    yaml_filename: "./occupancy_grid_map.yaml"
map_server_2d_n4:
  ros__parameters:
    yaml_filename: "./occupancy_grid_map.yaml"
