map_server:
    ros__parameters:
        yaml_filename: "test_map.yaml"
        map_type: "occupancy"
        free_thresh: 0.196
        occupied_thresh: 0.65
        mode: "trinary"
        negate: 0
