map_server:
  ros__parameters:
    yaml_filename: "/home/caorduno/map.yaml"
DwbController:
  ros__parameters:
    debug_trajectory_details: True
    min_vel_x: -0.26
    min_vel_y: 0.0
    max_vel_x: 0.26
    max_vel_y: 0.0
    max_vel_theta: 1.0
    min_speed_xy: 0.0
    # Set max XY speed to a large value so noisy Y data from IMU doesn't
    # prevent operation. Since this robot has no Y velocity capability, any Y
    # velocity reported in /odom data is due to slippage or noise, and there is
    # no need to reduce the robot's operating envelope when generating possible
    # trajectories.
    max_speed_xy: 100.0
    min_speed_theta: 0.0
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    decel_lim_theta: -3.2
local_costmap:
  local_costmap:
    ros__parameters:
      obstacle_layer:
        enabled: False
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
global_costmap:
  global_costmap:
    ros__parameters:
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: False
        marking: True
robot_centric_costmap:
  robot_centric_costmap:
    ros__parameters:
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      global_frame: "base_link"
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: False
        marking: True
