map_server:
    ros__parameters:
        map_name: "test_map.pgm"
        resolution: 0.1
        negate: 0
        occupied_thresh: 0.65
        free_thresh: 0.196
        mode: "trinary"
        origin: [-15.400000, -12.200000, 0.000000]
