map_server:
    ros__parameters:
        free_thresh: 0.196
        map_name: "test_map.pgm"
        map_type: "occupancy"
        mode: "trinary"
        negate: 0
        occupied_thresh: 0.65
        origin: [-15.400000, -12.200000, 0.000000]
        resolution: 0.1
