map_saver_server_2d_n1:
  ros__parameters:
    save_map_timeout: 2.0
    free_thresh_default: 0.25
    occupancy_thresh_default: 0.65
map_saver_server_2d_n2:
  ros__parameters:
    save_map_timeout: 1.0
    free_thresh_default: 0.25
    occupancy_thresh_default: 0.5
map_saver_server_2d_n3:
  ros__parameters:
    save_map_timeout: 3.0
    free_thresh_default: 0.3
    occupancy_thresh_default: 0.7
map_saver_server_2d_n4:
  ros__parameters:
    save_map_timeout: 4.0
    free_thresh_default: 0.2
    occupancy_thresh_default: 0.6
