map_saver_server_3d_n1:
  ros__parameters:
    save_map_timeout: 5.0
map_saver_server_3d_n2:
  ros__parameters:
    save_map_timeout: 1.0
map_saver_server_3d_n3:
  ros__parameters:
    save_map_timeout: 2.0
map_saver_server_3d_n4:
  ros__parameters:
    save_map_timeout: 3.0
