name: Colcon Build and Test

on:
  workflow_call:
    inputs:
      checkout_cache_key:
        required: true
        type: string
      overlay_cache_sha:
        required: true
        type: string
      overlay_ws:
        required: true
        type: string
      metadata:
        required: true
        type: string
      runs_on:
        required: true
        type: string
      tooler_image:
        required: true
        type: string
      validator_image:
        required: true
        type: string
    outputs:
      overlay_cache_key:
        value: ${{ jobs.test_colcon_workspace.outputs.overlay_cache_key }}

jobs:
  build_colcon_workspace:
    name: Build Workspace
    outputs:
      overlay_cache_key: ${{ steps.cache_overlay_info.outputs.overlay_cache_key }}
      build_packages: ${{ steps.check_differential.outputs.build_packages }}
    runs-on: ${{ inputs.runs_on }}
    container:
      image: ${{ inputs.tooler_image }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.overlay_ws }}/
    steps:
      - name: Restore checkout
        id: restore_checkout
        uses: actions/cache@v4
        with:
          fail-on-cache-miss: true
          path: ${{ inputs.overlay_ws }}/src/
          key: ${{ inputs.checkout_cache_key }}
      - name: Cache ccache
        id: cache_ccache
        uses: actions/cache@v4
        with:
          save-always: true
          path: |
            ${{ inputs.overlay_ws }}/.ccache
          key: "ccache-v1\
            -${{ github.ref }}\
            -${{ github.run_id }}\
            -${{ github.run_number }}\
            -${{ github.run_attempt }}"
          restore-keys: |
            ccache-v1-${{ github.ref }}
            ccache-v1-refs/heads/${{ github.head_ref }}
            ccache-v1-refs/heads/${{ github.base_ref }}
      - name: Cache overlay info
        id: cache_overlay_info
        run: |
          overlay_cache_key="overlay-v1"\
          "-${{ github.ref }}"\
          "-${{ inputs.overlay_cache_sha }}"\
          "-${{ github.run_id }}"\
          "-${{ github.run_number }}"\
          "-${{ github.run_attempt }}"
          echo "overlay_cache_key=${overlay_cache_key}" >> $GITHUB_OUTPUT
      - name: Cache overlay
        id: cache_overlay
        uses: actions/cache@v4
        with:
          save-always: true
          path: |
            ${{ inputs.overlay_ws }}/build
            ${{ inputs.overlay_ws }}/install
            ${{ inputs.overlay_ws }}/test_results
          key: ${{ steps.cache_overlay_info.outputs.overlay_cache_key }}
          restore-keys: |
            overlay-v1-${{ github.ref }}-${{ inputs.overlay_cache_sha }}
            overlay-v1-refs/heads/${{ github.head_ref }}-${{ inputs.overlay_cache_sha }}
            overlay-v1-refs/heads/${{ github.base_ref }}-${{ inputs.overlay_cache_sha }}
      - name: Check Differential
        id: check_differential
        shell: bash
        run: |
          marked_base_paths=$(find ./src -name "COLCON_MARK" -exec dirname {} \; | xargs)
          if [ -n "$marked_base_paths" ]; then
            echo "Differential build detected!"
            base_paths=$marked_base_paths
          else
            echo "Defaulting full build..."
            base_paths='./src'
          fi
          BUILD_PACKAGES=$(
            colcon list \
              --names-only \
              --base-paths $base_paths \
            | xargs)
          echo BUILD_PACKAGES: $BUILD_PACKAGES
          echo "build_packages=$BUILD_PACKAGES" >> $GITHUB_OUTPUT
      - name: Ccache Info
        run: |
          ccache -z # zero stats
          ccache -V # show version
          ccache -p # show config
      - name: Colcon Build
        id: colcon_build
        run: |
          . /opt/ros/$ROS_DISTRO/setup.sh
          colcon cache lock \
            --dirhash-reset
          colcon clean packages -y \
            --packages-select-cache-invalid \
            --packages-select-cache-key build \
            --base-select install
          colcon build \
            --packages-up-to \
              ${{ steps.check_differential.outputs.build_packages }} \
            --packages-skip-cache-valid \
            --mixin $OVERLAY_MIXINS
      - name: Ccache Stats
        if: always()
        run: |
          ccache -s # show stats
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ${{ inputs.overlay_ws }}/log/

  test_colcon_workspace:
    name: Test Workspace
    outputs:
      overlay_cache_key: ${{ needs.build_colcon_workspace.outputs.overlay_cache_key }}-${{ github.run_attempt }}
    runs-on: ${{ inputs.runs_on }}
    needs:
        - build_colcon_workspace
    container:
      image: ${{ inputs.validator_image }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.overlay_ws }}/
    steps:
      - name: Restore checkout
        id: restore_checkout
        uses: actions/cache@v4
        with:
          fail-on-cache-miss: true
          path: ${{ inputs.overlay_ws }}/src/
          key: ${{ inputs.checkout_cache_key }}
      - name: Cache overlay
        id: cache_overlay
        uses: actions/cache@v4
        with:
          save-always: true
          path: |
            ${{ inputs.overlay_ws }}/build
            ${{ inputs.overlay_ws }}/install
            ${{ inputs.overlay_ws }}/test_results
          key: ${{ needs.build_colcon_workspace.outputs.overlay_cache_key }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ needs.build_colcon_workspace.outputs.overlay_cache_key }}
      - name: Colcon Test
        id: colcon_test
        run: |
          . install/setup.sh
          colcon test \
            --packages-select \
              ${{ needs.build_colcon_workspace.outputs.build_packages }} \
            --packages-skip-cache-valid
          TEST_FAILURES=$(
              colcon list \
              --names-only \
              --packages-select-test-failures \
              | xargs)
          echo TEST_FAILURES: $TEST_FAILURES
          TEST_UNFINISHED=$(
            colcon list \
            --names-only \
            --packages-skip-test-passed \
            | xargs)
          echo TEST_UNFINISHED: $TEST_UNFINISHED
          colcon test-result \
            --verbose
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: ${{ inputs.overlay_ws }}/log/
      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ inputs.overlay_ws }}/test_results/
