---
name: Check CI Image

on:
  schedule:
  # 7am UTC, 12am PDT
  - cron:  '0 7 * * *'

jobs:
  check_ci_image:
    name: Check CI Image
    runs-on: ubuntu-latest
    container:
      image: rosplanning/navigation2:main
    steps:
      - name: "Initialize environment"
        run: |
          echo "TRIGGER=false" >> $GITHUB_ENV
      - name: "Check apt updates"
        env:
          SOURCELIST: sources.list.d/ros2.list
        run: |
          apt-get update \
            -o Dir::Etc::sourcelist="${SOURCELIST}"
          apt-get --simulate upgrade \
            -o Dir::Etc::sourcelist="${SOURCELIST}" \
            | grep "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded." \
            && echo "No apt updates" || echo "TRIGGER=true" >> $GITHUB_ENV
      - name: "Dispatch Rebuild CI Image"
        if: ${{ fromJSON(env.TRIGGER) }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: rebuild-ci-image
          client-payload: '{"no_cache": "true"}'
