---
name: Rebuild CI Image

on:
  repository_dispatch:
    types: [rebuild-ci-image]
  push:
    branches:
    - main
    paths:
    - '**/package.xml'
    - '**/*.repos'
    - 'Dockerfile'

jobs:
  rebuild_ci_image:
    name: Rebuild CI Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set build config
        id: config
        run: |
          timestamp=$(date --utc +%Y%m%d%H%M%S)
          echo "::set-output name=timestamp::${timestamp}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          no-cache: ${{ github.event.client_payload.no_cache }}
          cache-from: type=registry,ref=rosplanning/navigation2:main
          cache-to: type=inline
          target: builder
          tags:
            - rosplanning/navigation2:main
            - rosplanning/navigation2:main-${{ steps.config.outputs.timestamp }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
