---
name: Update CI Image

on:
  schedule:
  # 7am UTC, 12am PDT
  - cron:  '0 7 * * *'
  push:
    branches:
    - main
    paths:
    - '**/package.xml'
    - '**/*.repos'
    - 'Dockerfile'

jobs:
  check_ci_files:
    name: Check CI Files
    runs-on: ubuntu-latest
    steps:
      - name: "Initialize environment"
        run: |
          echo "TRIGGER=false" >> $GITHUB_ENV
          echo "NO_CACHE=false" >> $GITHUB_ENV
      - name: "Check package updates"
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "TRIGGER=true" >> $GITHUB_ENV
  check_ci_image:
    name: Check CI Image
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    container:
      image: rosplanning/navigation2:main
    steps:
      - name: "Check apt updates"
        env:
          SOURCELIST: sources.list.d/ros2.list
        run: |
          apt-get update \
            -o Dir::Etc::sourcelist="${SOURCELIST}"
          apt-get --simulate upgrade \
            -o Dir::Etc::sourcelist="${SOURCELIST}" \
            | grep "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded." \
            && echo "No apt updates" || echo "TRIGGER=true" >> $GITHUB_ENV
          echo "NO_CACHE=true" >> $GITHUB_ENV
  rebuild_ci_image:
    name: Rebuild CI Image
    if: ${{ fromJSON(env.TRIGGER) }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set build config
        id: config
        run: |
          timestamp=$(date --utc +%Y%m%d%H%M%S)
          echo "::set-output name=timestamp::${timestamp}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          no-cache: ${{ fromJSON(env.NO_CACHE) }}
          cache-from: type=registry,ref=rosplanning/navigation2:main
          cache-to: type=inline
          target: builder
          tags:
            - rosplanning/navigation2:main
            - rosplanning/navigation2:main-${{ steps.config.outputs.timestamp }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
